### PR TITLE
Mark arguments as nullable in AddCspHeaders

### PR DESCRIPTION
**Pull request by jnoordsij**
Credits to my codestyle checker that noticed this while I was looking through the source code.

### CODE REVIEW

**Comment by freekmurze** [comment]
Right now our code says that if the function is called without the argument, just use null. Detail: users are not allowed to pass `null`.

You change allows `null` to be passed, but we don't want to encourage that.

So I'm passing on this for now.

**Comment by jnoordsij** [comment]
> You change allows `null` to be passed, but we don't want to encourage that.

Actually in the PHP 8.0 and above, using `null` as default makes the type implicitly nullable (see https://www.php.net/manual/en/functions.arguments.php above `Example #10`), so this really is simply a cosmetic/style change and does not change any functionality for users. 

Though I do agree not adding it to the typehint is somewhat of an encouragement not to pass `null`.

**Comment by freekmurze** [comment]
Oh TIL 🙂 

> Though I do agree not adding it to the typehint is somewhat of an encouragement not to pass null.

Yeah, going to leave it like this, thanks!

**Comment by jnoordsij** [comment]
@freekmurze just a FYI: I remember this PR and learning about implicit nullability in the progress when reading today about [PHP 8.4: Implicitly nullable parameter declarations deprecated](https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated), so maybe it is finally time to merge this ;)

**Pull request closed without merging**
