### PR TITLE
Add value constant for “data:”

### PR DESCRIPTION
**Pull request by gbuckingham89**
I've simply added a new vale constant for "data:" which allows the loading of resources via the data scheme (eg Base64 encoded images).

It came about because the [barryvdh/laravel-debugbar](https://github.com/barryvdh/laravel-debugbar) package uses base64 encoded images for it's icons.

This is my first pull request, so if I've missed anything, please let me know!

### CODE REVIEW

**Comment by Gummibeer** [comment]
I've not tested it but so far I got this won't work.
Source: https://stackoverflow.com/a/18449556/4907524

* Value constants are quoted by this package (?)
* Data is a scheme which has to stay unquoted

To implement this I would recommend a second class `Scheme` which holds all available schemes.

**Comment by Gummibeer** [comment]
Ok related to the quotes `isSpecialDirective()` uses a hardcoded list. So no problem.
But I still would like another constant holder class more to keep it cleaner.

**Comment by freekmurze** [comment]
@Gummibeer Could you give some more info on "But I still would like another constant holder class more to keep it cleaner."?

**Comment by Gummibeer** [comment]
At the moment the `Value` class holds all keywords - that should get escaped. Now the request is to add also schemes as constants. I would rename the `Value` class to `Keyword` (this is optional) and add a second class `Scheme` which holds "all" available schemes (http, https, blob, data etc).
With this the `isSpecialDirective()` method could also use `ReflectionClass` and use all constants instead of having a hardcoded list.

**Comment by freekmurze** [comment]
I'm going to allow this for now. Might restructure things in a future major version. Thanks for your input @Gummibeer

**Comment by Gummibeer** [comment]
@freekmurze 100% ok - primary because it would be breaking.
Will you add https://github.com/spatie/laravel-csp/labels/revisited%20for%20v2 ?

**Pull request merged**
