### PR TITLE
Add scheme values

### PR DESCRIPTION
**Pull request by Gummibeer**
**breaking**

This adds also `blob`, `http/s` scheme in addition to #38 

The renaming of the `Value` class and the move of the `data` constant are the breaking changes. I'm open for discussions and can also send a PR that adds these constants to the `Value` class to keep this open for `v2`.

### CODE REVIEW

**Comment by freekmurze** [comment]
Thank you for this! We'll probably create a v2 when Laravel 5.7 gets released.

**Comment by freekmurze** [comment]
Could you fix the merge conflicts and update the readme?

**Comment by Gummibeer** [comment]
@freekmurze now it passes also the new `NO_VALUE` test. Because the `NO_VALUE` isn't a keyword or scheme I've kept it in the `Value` class. Let me know if this is ok/right or if you want it anywhere.
In the `Keyword` class it produced an error in the `isKeyword()` method.

The only thing I struggle with is the kind of code-duplication in the `addDirective()` and `__toString()` method. I will take a look if it's possible to reduce this a bit.

**Comment by Gummibeer** [comment]
@freekmurze my change to the `addDirective()` method is based on my comment in https://github.com/spatie/laravel-csp/pull/44#issuecomment-415149740 - `NO_VALUE` means no value, so no reason to allow it as child of an array and it should be compared in a type-safe way to the constant value and not be a weak comparison `empty()`.
I've also added the `bool` param type to `$values` because of the `NO_VALUE` constant which isn't a string or array. The only idea to improve this would be `null`. `null` would be, for me, the correct representation of _no value_ and wouldn't "allow" two values if it's put into the `@param` type-hint.
Can you tell me your opinion to these points and I will update this PR if needed.

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
